#!/usr/bin/perl
use strict;
use utf8;

if (@ARGV != 2) {
    printf STDERR "ngram_diff file1 file2\n";
    exit 1;
}

my $file1 = shift @ARGV;
my $file2 = shift @ARGV;

my %count=();

open(F1, $file1) || die "Fatal:$!";
while(my $ngram = <F1>){
    $ngram =~ s/[\r\n]$//g;
    $count{$ngram}++;
}
close(F1);

open(F2, $file2) || die "Fatal:$!";
while(my $ngram = <F2>){
    $ngram =~ s/[\r\n]$//g;
    $count{$ngram}=0;
}
close(F2);

foreach my $ngram (keys(%count)) {
    if ($count{$ngram}>0) {
	printf "%s\n", $ngram;
    }
}
